@startuml
package com.github.kokasumi.design.principles.srp.user.dependency {
    interface IUserBO {
        + void setUserID(String userID);
        + String getUserID();
        + void setPassword(String password);
        + String getPassword();
        + void setUserName(String userName);
        + String getUserName();
    }
    note top of IUserBO: 负责用户的属性
    interface IUserBiz {
        + boolean changePassword(IUserBO userBO,String oldPassword, String newPassword);
        + boolean deleteUser(IUserBO userBO);
    }
    note top of IUserBiz: 负责用户的行为
    IUserBO <...right IUserBiz: 依赖
    class UserBO implements IUserBO {}
    class UserBiz implements IUserBiz {}
}
@enduml