@startuml
package com.github.kokasumi.design.principles.srp.user.counter {
interface IUserInfo {
 + void setUserID(String userID);
 + String getUserID();
 + void setPassword(String password);
 + String getPassword();
 + void setUserName(String userName);
 + String getUserName();
 + boolean changePassword(String oldPassword,String newPassword);
 + boolean deleteUser();
}
class UserInfo implements IUserInfo {
}
}
@enduml