@startuml
'https://plantuml.com/class-diagram
class UserBO {
    - userId : String
    - userName : String
    - password : String
    - email : String
    - telephone : String
    - province : String
    - city : String
    - region : String
    - detailAddress : String
}
note top of UserBO: 负责维护用户属性
interface IUserBiz {
    + changePassword(userBO : UserBO, oldPassword : String,newPassword : String) : boolean
    + deleteUser(userBO : UserBO) : boolean
}
note top of IUserBiz: 负责维护用户行为
UserBO <...right IUserBiz: 依赖
class UserBiz implements IUserBiz {}
@enduml